version: '3'
services:
  web:
    container_name: iot-web
    build: 
      context: . 
      dockerfile: ./docker/Dockerfile-web
    ports:
      - 3000:3000
    command: ['npm', 'run', 'start']
    volumes:
      - ./web:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    networks:
      - frontend
  server:
    build:
      context: . 
      dockerfile: ./docker/Dockerfile-server
    restart: always
    ports: 
      - "3001:3001"
    command: ['npm', 'run', 'dev']
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      WAIT_HOSTS: database:27017
    networks:
      - frontend
      - backend
  database:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=example
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=api
    volumes:
      - "./data/db:/data/db"
    ports:
      - "27017:27017"
    command: "mongod --smallfiles --logpath=/var/log/mongodb/mongodb.log"
    networks:
      - backend
networks: 
  frontend:
    driver: bridge
  backend:
    driver: bridge