version: '3'
services:
  # web:
  #   build: 
  #     context: . 
  #     dockerfile: ./docker/Dockerfile-web
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - "./web:/app"
  #   networks:
  #     - frontend
  server:
    build:
      context: . 
      dockerfile: ./docker/Dockerfile-server
    restart: always
    ports: 
      - "3001:3001"
    volumes:
      - "./server:/app"
    environment:
      WAIT_HOSTS: database:27017
    networks:
      - frontend
      - backend
  database:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=example
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=api
    volumes:
      - "./data/db:/data/db"
    expose:
      - 27017
    command: "mongod --smallfiles --logpath=/var/log/mongodb/mongodb.log"
    networks:
      - backend
networks: 
  frontend:
    driver: bridge
  backend:
    driver: bridge